# Generated by Django 2.1 on 2021-03-15 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_account_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_date', models.DateTimeField(verbose_name='transaction date')),
                ('accounting_period', models.DateField(verbose_name='accounting period')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EMI.Accounts')),
            ],
        ),
    ]
