# Generated by Django 2.1 on 2021-03-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='bank_account_number',
            field=models.IntegerField(verbose_name=15),
        ),
    ]
