# Generated by Django 2.1 on 2021-03-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMI', '0002_auto_20210315_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='bank_account_number',
            field=models.CharField(max_length=15),
        ),
    ]
